// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ranking_max_cpp
List ranking_max_cpp(DataFrame data, int k, List max_par_groupe, NumericVector poids_positions);
RcppExport SEXP _Ranking_ranking_max_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP max_par_groupeSEXP, SEXP poids_positionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< List >::type max_par_groupe(max_par_groupeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poids_positions(poids_positionsSEXP);
    rcpp_result_gen = Rcpp::wrap(ranking_max_cpp(data, k, max_par_groupe, poids_positions));
    return rcpp_result_gen;
END_RCPP
}
// ranking_max_dp_heap_cpp
Rcpp::List ranking_max_dp_heap_cpp(Rcpp::DataFrame data, int k, Rcpp::List max_par_groupe, Rcpp::Nullable<Rcpp::NumericVector> poids_positions, int beam_size, bool verbose);
RcppExport SEXP _Ranking_ranking_max_dp_heap_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP max_par_groupeSEXP, SEXP poids_positionsSEXP, SEXP beam_sizeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type max_par_groupe(max_par_groupeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type poids_positions(poids_positionsSEXP);
    Rcpp::traits::input_parameter< int >::type beam_size(beam_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ranking_max_dp_heap_cpp(data, k, max_par_groupe, poids_positions, beam_size, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _Ranking_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Ranking_ranking_max_cpp", (DL_FUNC) &_Ranking_ranking_max_cpp, 4},
    {"_Ranking_ranking_max_dp_heap_cpp", (DL_FUNC) &_Ranking_ranking_max_dp_heap_cpp, 6},
    {"_Ranking_rcpp_hello", (DL_FUNC) &_Ranking_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Ranking(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
