# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ranking_max_cpp <- function(data, k, max_par_groupe, poids_positions) {
    .Call(`_Ranking_ranking_max_cpp`, data, k, max_par_groupe, poids_positions)
}

ranking_max_dp_heap_cpp <- function(data, k, max_par_groupe, poids_positions = NULL, beam_size = 5000L, verbose = FALSE) {
    .Call(`_Ranking_ranking_max_dp_heap_cpp`, data, k, max_par_groupe, poids_positions, beam_size, verbose)
}

rcpp_hello <- function() {
    .Call(`_Ranking_rcpp_hello`)
}

